-- MySQL Script generated by MySQL Workbench
-- Fri May 11 10:44:01 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema TINYHIPPO
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TINYHIPPO
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TINYHIPPO` DEFAULT CHARACTER SET utf8 ;
USE `TINYHIPPO` ;

-- -----------------------------------------------------
-- Table `TINYHIPPO`.`Edit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TINYHIPPO`.`Edit` (
  `customerID` INT UNSIGNED NOT NULL,
  `orderID` INT UNSIGNED NOT NULL,
  `editedTime` DATE NOT NULL,
  PRIMARY KEY (`customerID`, `orderID`),
  UNIQUE INDEX `customerID_UNIQUE` (`customerID` ASC),
  UNIQUE INDEX `orderID_UNIQUE` (`orderID` ASC));


-- -----------------------------------------------------
-- Table `TINYHIPPO`.`Resturant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TINYHIPPO`.`Resturant` (
  `resturantID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `resturantName` VARCHAR(50) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`resturantID`),
  UNIQUE INDEX `resturantID_UNIQUE` (`resturantID` ASC),
  UNIQUE INDEX `resturantName_UNIQUE` (`resturantName` ASC));


-- -----------------------------------------------------
-- Table `TINYHIPPO`.`Table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TINYHIPPO`.`Table` (
  `tableID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tableNumber` INT UNSIGNED NOT NULL,
  `resturantID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`tableID`, `resturantID`),
  UNIQUE INDEX `tableNumber_UNIQUE` (`tableNumber` ASC),
  UNIQUE INDEX `tableID_UNIQUE` (`tableID` ASC),
  INDEX `fk_Table_Resturant1_idx` (`resturantID` ASC),
  CONSTRAINT `fk_Table_Resturant1`
    FOREIGN KEY (`resturantID`)
    REFERENCES `TINYHIPPO`.`Resturant` (`resturantID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `TINYHIPPO`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TINYHIPPO`.`Customer` (
  `customerID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `customerName` VARCHAR(20) NOT NULL,
  `orderID` INT UNSIGNED NOT NULL,
  `tableID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`customerID`, `orderID`, `tableID`),
  UNIQUE INDEX `customer_id_UNIQUE` (`customerID` ASC),
  INDEX `fk_Customer_Edit1_idx` (`orderID` ASC),
  INDEX `fk_Customer_Table1_idx` (`tableID` ASC),
  UNIQUE INDEX `customerName_UNIQUE` (`customerName` ASC),
  CONSTRAINT `fk_Customer_Edit1`
    FOREIGN KEY (`orderID`)
    REFERENCES `TINYHIPPO`.`Edit` (`orderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Customer_Table1`
    FOREIGN KEY (`tableID`)
    REFERENCES `TINYHIPPO`.`Table` (`tableID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `TINYHIPPO`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TINYHIPPO`.`Order` (
  `orderID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `orderDishes` VARCHAR(500) NOT NULL,
  `total` FLOAT NOT NULL,
  `isPaid` VARCHAR(10) NOT NULL,
  `customerID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`orderID`, `customerID`),
  INDEX `fk_Order_Edit_idx` (`customerID` ASC),
  UNIQUE INDEX `orderID_UNIQUE` (`orderID` ASC),
  CONSTRAINT `fk_Order_Edit`
    FOREIGN KEY (`customerID`)
    REFERENCES `TINYHIPPO`.`Edit` (`customerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `TINYHIPPO`.`QRlink`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TINYHIPPO`.`QRlink` (
  `linkID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `linkImage` VARCHAR(255) NOT NULL,
  `tableID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`linkID`, `tableID`),
  UNIQUE INDEX `linkID_UNIQUE` (`linkID` ASC),
  INDEX `fk_QRlink_Table1_idx` (`tableID` ASC),
  CONSTRAINT `fk_QRlink_Table1`
    FOREIGN KEY (`tableID`)
    REFERENCES `TINYHIPPO`.`Table` (`tableID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `TINYHIPPO`.`Menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TINYHIPPO`.`Menu` (
  `menuID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `menuTitle` VARCHAR(45) NOT NULL,
  `resturantID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`menuID`, `resturantID`),
  UNIQUE INDEX `menuID_UNIQUE` (`menuID` ASC),
  INDEX `fk_Menu_Resturant1_idx` (`resturantID` ASC),
  CONSTRAINT `fk_Menu_Resturant1`
    FOREIGN KEY (`resturantID`)
    REFERENCES `TINYHIPPO`.`Resturant` (`resturantID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `TINYHIPPO`.`DishType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TINYHIPPO`.`DishType` (
  `dishTypeID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `dishTypeName` VARCHAR(45) NOT NULL,
  `menuID` INT UNSIGNED NOT NULL,
  `resturantID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`dishTypeID`, `menuID`, `resturantID`),
  UNIQUE INDEX `dishTypeID_UNIQUE` (`dishTypeID` ASC),
  INDEX `fk_DishType_Menu1_idx` (`menuID` ASC, `resturantID` ASC),
  CONSTRAINT `fk_DishType_Menu1`
    FOREIGN KEY (`menuID` , `resturantID`)
    REFERENCES `TINYHIPPO`.`Menu` (`menuID` , `resturantID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `TINYHIPPO`.`Dish`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TINYHIPPO`.`Dish` (
  `dishID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `dishName` VARCHAR(255) NOT NULL,
  `price` FLOAT NOT NULL,
  `dishImage` VARCHAR(255) NOT NULL,
  `dishComment` VARCHAR(255) NOT NULL,
  `dishHot` INT UNSIGNED NOT NULL,
  `seletedNumber` INT UNSIGNED NOT NULL,
  `monthlySales` INT UNSIGNED NOT NULL,
  `orderID` INT UNSIGNED NOT NULL,
  `dishTypeID` INT UNSIGNED NOT NULL,
  `menuID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`dishID`, `orderID`, `dishTypeID`, `menuID`),
  UNIQUE INDEX `dishID_UNIQUE` (`dishID` ASC),
  INDEX `fk_Dish_DishType1_idx` (`dishTypeID` ASC),
  INDEX `fk_Dish_Order1_idx` (`orderID` ASC),
  INDEX `fk_Dish_Menu1_idx` (`menuID` ASC),
  CONSTRAINT `fk_Dish_DishType1`
    FOREIGN KEY (`dishTypeID`)
    REFERENCES `TINYHIPPO`.`DishType` (`dishTypeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dish_Order1`
    FOREIGN KEY (`orderID`)
    REFERENCES `TINYHIPPO`.`Order` (`orderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dish_Menu1`
    FOREIGN KEY (`menuID`)
    REFERENCES `TINYHIPPO`.`Menu` (`menuID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
